LMM_WebClient/Controllers/ClassController.cs
using LMM_WebClient.Entity;
using LMM_WebClient.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net.Http.Headers;
using System.Text;
using static System.Net.WebRequestMethods;

namespace LMM_WebClient.Controllers
{
    public class ClassController : Controller
    {
        private IConfiguration configuration;
        private HttpClient client = null;
        private string apiurl = "";

        public ClassController(IConfiguration _configuration)
        {
            configuration = _configuration;
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            apiurl = configuration.GetValue<string>("PortUrl") + "api/Classes";

        }
        // GET: ClassController
        public async Task<IActionResult> Index()
		{
			List<Class> items = new List<Class>();
			String userId = (String)HttpContext.Session.GetString("userId");
            string apiEndpoint = apiurl + "/GetClassesByUserId?" + "userId=" + userId;

			HttpResponseMessage response = await client.GetAsync(apiEndpoint);
            string strData = await response.Content.ReadAsStringAsync();


			if (!strData.Equals("[]"))
			{
				items = JsonConvert.DeserializeObject<List<Class>>(strData);

			}
            return View(items);
        }

        // GET: ClassController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Class item = new Class();
			string apiEndpoint = apiurl + "/" + id;
            String materialUrl = "https://localhost:5000/api/Materials/getbyclass/" + id;
            HttpResponseMessage responeMaterial = await client.GetAsync(materialUrl);
            //HttpResponseMessage response = await client.GetAsync(apiEndpoint);
			//string strData = await response.Content.ReadAsStringAsync();
            string materialData = await responeMaterial.Content.ReadAsStringAsync();
            List<Material> listMaterial = JsonConvert.DeserializeObject<List<Material>>(materialData);
            ViewBag.ListMaterial = listMaterial;
            ViewBag.classId = id;

            //         if (strData != null)
            //{
            //	item = JsonConvert.DeserializeObject<Class>(strData);

            //}

            return View(item);
        }
		public async Task<IActionResult> Create()
		{
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("JWT"));
			String userId = (String)HttpContext.Session.GetString("userId");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(string classCode, string classDescription, string userId)
		{
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("JWT"));
			if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(classCode) || string.IsNullOrEmpty(classDescription))
			{
				return RedirectToAction("Index");
			}
			CreateClassDTO createClassDTO = new CreateClassDTO
			{
				ClassCode = classCode,
				Description = classDescription,
				CreatorId = Int32.Parse(userId),
			};
			string json = JsonConvert.SerializeObject(createClassDTO);
			StringContent content = new StringContent(json, Encoding.UTF8, "application/json");


			string apiEndpoint = apiurl + "/CreateClass";
			HttpResponseMessage response = await client.PostAsync(apiEndpoint, content);
			string strData = await response.Content.ReadAsStringAsync();
			return RedirectToAction("Index");
		}

		// GET: ClassController/Details/5
		public async Task<IActionResult> Search(string classCode, string userId)
		{
            List<ClassDTO> items = null;
			if (string.IsNullOrEmpty(classCode))
			{
				return View(items);
			}
			string apiEndpoint = apiurl + "/Search?" + "classCode=" + classCode + "&userId=" + Int32.Parse(userId);

			HttpResponseMessage response = await client.GetAsync(apiEndpoint);
			string strData = await response.Content.ReadAsStringAsync();


			if (!strData.Equals("[]"))
			{
				items = JsonConvert.DeserializeObject<List<ClassDTO>>(strData);

			}

			return View(items);
		}

        public async Task<ActionResult> JoinClass(string userId, string classId)
		{
			if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(classId))
			{
				return RedirectToAction("Index");
			}
			JoinClassDTO joinClassDTO = new JoinClassDTO
			{
				ClassId = Int32.Parse(classId),
				UserId = Int32.Parse(userId)
			};

			string json = JsonConvert.SerializeObject(joinClassDTO);

			StringContent content = new StringContent(json, Encoding.UTF8, "application/json");

			string apiEndpoint = apiurl + "/JoinClass";

			HttpResponseMessage response = await client.PostAsync(apiEndpoint, content);
			string strData = await response.Content.ReadAsStringAsync();


			return RedirectToAction("Index");
		}

		public async Task<ActionResult> LeaveClass(string userId, string classId)
		{
			if (string.IsNullOrEmpty(userId) || string.IsNullOrEmpty(classId))
			{
				return RedirectToAction("Index");
			}
			string apiEndpoint = apiurl + "/LeaveClass?" + "classId=" + Int32.Parse(classId) + "&userId=" + Int32.Parse(userId);

			HttpResponseMessage response = await client.DeleteAsync(apiEndpoint);
			string strData = await response.Content.ReadAsStringAsync();


			return RedirectToAction("Index");
		}

		// GET: ClassController/Edit/5
		public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClassController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClassController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClassController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

LMM_WebClient/Views/Class/Create.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@model IEnumerable<LMM_WebClient.Models.ClassDTO>
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<html lang="en">
<head>
	<title>Learning Material Management</title>
	<meta charset="UTF-8">
	<!-- Stylesheets -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/font-awesome.min.css" />
	<link rel="stylesheet" href="~/css/style.css" />

	<style>
		body {
			background: url('@Url.Content("~/img/bg.jpg")') no-repeat center center fixed;
			background-size: cover;
			/* other CSS properties */
		}

		.wrapper {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
		}
	</style>
</head>
<body>

	<!-- Header section end -->
	<!-- Hero section -->
	<div class="wrapper">
		<section class="hero-section set-bg">
			<div class="container mx-auto">
				<!-- search section -->
				<section class="search-section">
					<div class="container">
						<div class="search-warp">
							<div class="section-title text-white">
								<h2>Create your class</h2>
							</div>
							<div class="row">
								<div class="col-md-10 offset-md-1">
									<!-- search form -->
									<form asp-action="Create" method="post">
										<div class="form-group">
											<label for="classCode">Class Code:</label>
											<input type="text" class="form-control" id="classCode" name="classCode" placeholder="Enter Class Code" required>
											<label for="classCode">Class Description:</label>
											<input type="text" class="form-control" id="classDescription" name="classDescription" placeholder="Enter Class Description" required>
											<input type="hidden" class="form-control" id="userId" name="userId" value="@HttpContextAccessor.HttpContext.Session.GetString("userId")">
										</div>
										<button type="submit" class="btn btn-primary">Create Class</button>
									</form>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		</section>
	</div>
</body>
</html>

LMM_WebClient/Views/Class/Details.cshtml
@using LMM_WebClient.Entity
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>
<body>
    <section class="class-section spad">
        <div class="container">
            <h2>Class Materials</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Material Name</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody id="listMaterial">
                    @{
                        var listMaterial = ViewBag.ListMaterial as List<Material>;
                    }

                    @if (listMaterial != null)
                    {
                        @foreach (var material in listMaterial)
                        {
                            <tr>
                                <td><a href="@material.FilePath" download>@material.Title</a></td>
                                <td><a class="btn btn-primary" href="Materials/Delete">Delete</a></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>

            <button id="abc" type="button" class="btn btn-primary" data-toggle="modal" data-target="#uploadModal">Upload Material</button>

            <div class="modal fade" id="uploadModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Upload Material</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-body">
                            <form>
                                <div class="form-group">
                                    <label for="fileInput">Select file:</label>
                                    <input type="hidden" class="form-control" value="@ViewBag.classId" id="classId" />
                                    <input type="file" class="form-control-file" id="fileInput">
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" id="uploadButton" class="btn btn-success" data-dismiss="modal">Upload</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

 <script>
        function ShowAllOrders() {
            $("table tbody").html("");
            var classId = $('#classId').val();
            $.ajax({
                url: "https://localhost:5000/api/Materials/getbyclass/" + classId,
                type: "GET",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result, status, xhr) {
                    console.log(result);
                    $.each(result, function (index, result) {
                        $("tbody").append($("<tr>"));
                        var filePath = result["title"];
                        console.log(filePath);
                        appendElement = $("tbody tr").last();
                        appendElement.append($("<td style=\"display: none\">").html(result["materialId"]));
                        appendElement.append($("<td display=\"none\">").html(result["title"]));
                        appendElement.append($("<td>").html("<button class=\"btn btn-primary delete\" href=\""
                            + "\">Delete</a>"));
                    })
                },
                error: function (xhr, status, error) {
                    console.log(xhr);
                }
            });
        };
        $(document).ready(function () {
            ShowAllOrders();

        });
        $(function () {
            $('#uploadButton').on('click', function (e) {
                e.preventDefault();
                var formdata = new FormData();
                var file = $('#fileInput')[0];
                var classId = $('#classId').val();
                formdata.append('file', file.files[0]);
                formdata.append('classId', classId);
                console.log(file);
                console.log(classId);

                // Gửi yêu cầu lên server
                $.ajax({
                    url: "https://localhost:5000/api/Materials",
                    type: 'POST',
                    data: formdata,
                    processData: false,
                    contentType: false,
                    success: function (index,result) {
                        ShowAllOrders();
                    },
                    error: function () {
                        alert('Failed to upload material');
                    }
                });
            });
        });
        $("table").on("click", "button.delete", function () {
            var productId = $(this).parents("tr").find("td:nth-child(1)").text();
            console.log(productId);
            $.ajax({
                url: "https://localhost:5000/api/Materials/" + productId,
                type: "delete",
                contentType: "application/json",
                success: function (result, status, xhr) {
                    ShowAllOrders();
                },
                error: function (xhr, status, error) {
                    console.log(xhr)
                }
            });
        });
 </script>

</body>
</html>

LMM_WebClient/Views/Class/Index.cshtml
@model IEnumerable<LMM_WebClient.Entity.Class>

<html lang="en">
<head>
	<title>Learning Material Management</title>
	<meta charset="UTF-8">
	<meta name="description" content="Learning Material Management">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/font-awesome.min.css" />
	<link rel="stylesheet" href="~/css/style.css" />

	<style>
		body {
			background: url('@Url.Content("~/img/bg.jpg")') no-repeat center center fixed;
			background-size: cover;
			/* other CSS properties */
		}

		.wrapper {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
		}
	</style>
</head>
<body>
	<!-- class section -->
	<div class="wrapper">
	<section class="class-section spad">
		<div class="container">
			<div class="section-title">
				<h2>Your class:</h2>
			</div>
			<div class="row">
				@foreach (var item in Model)
				{

						<div class="col-sm-4 finance">
					<!-- categorie -->
						<a asp-action="Details" asp-route-id="@item.ClassId">
							<!-- course -->
								<div class="course-item">
									<div class="course-thumb set-bg" style="background: url('@Url.Content("~/img/courses/1.jpg")')">
									</div>
									<div class="course-info">
										<div class="course-text">
											<h5>@Html.DisplayFor(modelItem => item.ClassCode)</h5>
											<p>@Html.DisplayFor(modelItem => item.Description)</p>
										</div>
									</div>
								</div>
							</a>
						</div>
					<!-- categorie -->
				}

			</div>
			</div>
	</section>
	</div>
	<!-- class section end -->
	<!-- Hero section end -->
</body>
</html>

LMM_WebClient/Views/Class/Search.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@model IEnumerable<LMM_WebClient.Models.ClassDTO>
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<html lang="en">
<head>
	<title>Learning Material Management</title>
	<meta charset="UTF-8">
	<!-- Stylesheets -->
	<link rel="stylesheet" href="~/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/font-awesome.min.css" />
	<link rel="stylesheet" href="~/css/style.css" />

	<style>
		body {
			background: url('@Url.Content("~/img/bg.jpg")') no-repeat center center fixed;
			background-size: cover;
			/* other CSS properties */
		}

		.wrapper {
			display: flex;
			justify-content: center;
			align-items: center;
			height: 100vh;
		}
	</style>
</head>
<body>

	<!-- Header section end -->
	<!-- Hero section -->
	<div class="wrapper">
	<section class="hero-section set-bg">
		<div class="container mx-auto">
			<!-- search section -->
			<section class="search-section">
				<div class="container">
					<div class="search-warp">
						<div class="section-title text-white">
							<h2>Search your class</h2>
						</div>
						<div class="row">
							<div class="col-md-10 offset-md-1">
								<!-- search form -->
								<form asp-action="Search" method="get">
										<div class="form-group">
											<label for="classCode">Search by Class Code:</label>
											<input type="text" class="form-control" id="classCode" name="classCode" placeholder="Enter Class Code">
											<input type="hidden" class="form-control" id="userId" name="userId" value="@HttpContextAccessor.HttpContext.Session.GetString("userId")">
										</div>
									<button type="submit" class="btn btn-primary">Search</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</section>


			<!-- course section -->
			<section class="course-section spad pb-0">
				<div class="course-warp">
					<div class="row course-items-area">
						@if (Model != null)
						{
							@foreach (var item in Model)
							{
								<!-- course -->
								<div class="col-sm-4 finance">
									<div class="course-item">
										<div class="course-thumb set-bg" style="background: url('@Url.Content("~/img/courses/1.jpg")')">
										</div>
										<div class="course-info">
											<div class="course-text">
												<h5>@Html.DisplayFor(modelItem => item.Class.ClassCode)</h5>
													<p>@Html.DisplayFor(modelItem => item.Class.Description)</p>
													@if (item.IsEnrolled)
													{
														<p class="site-btn" style="background-color: greenyellow">Enrolled.</p>
													}
													else
													{
														<a asp-area="" asp-controller="Class" asp-action="JoinClass" asp-route-classId="@item.Class.ClassId" asp-route-userId="@HttpContextAccessor.HttpContext.Session.GetString("userId")" class="site-btn">Enroll me.</a>
													}
											</div>
										</div>
									</div>
								</div>
							}
						}
					</div>
				</div>
			</section>
		</div>
	</section>
	</div>
</body>
</html>